name: Node.js CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "*"
#  pull_request:
#    branches: [ "master" ]

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    steps:
      - name: match-tag-to-package-version
        id: match-tag-to-package-version
        uses: geritol/match-tag-to-package-version@0.2.0
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm install
    - run: npm run build
    - run: pm2 startOrReload ecosystem.config.js --update-env
